/**
 * Embed role packs, constitution, and icons into TypeScript so the published
 * server never calls fs (clears Socket "filesystem access" on our package).
 */
import {
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "src", "generated");
const outFile = join(outDir, "embedded.ts");

function asTsString(value) {
  return JSON.stringify(value);
}

function dataUri(filePath, mimeType) {
  const buf = readFileSync(filePath);
  if (mimeType === "image/svg+xml") {
    return `data:${mimeType},${encodeURIComponent(buf.toString("utf8"))}`;
  }
  return `data:${mimeType};base64,${buf.toString("base64")}`;
}

const packsDir = join(root, "src", "roles", "packs");
const packFiles = readdirSync(packsDir)
  .filter((f) => f.endsWith(".md"))
  .sort();

const packs = {};
for (const file of packFiles) {
  const id = file.replace(/\.md$/, "");
  packs[id] = readFileSync(join(packsDir, file), "utf8");
}

const constitution = readFileSync(
  join(root, "src", "constitution.md"),
  "utf8"
).trim();

const assets = join(root, "src", "assets");
const icons = [
  {
    src: dataUri(join(assets, "logo.svg"), "image/svg+xml"),
    mimeType: "image/svg+xml",
    sizes: ["any"],
    theme: "dark",
  },
  {
    src: dataUri(join(assets, "logo-light.svg"), "image/svg+xml"),
    mimeType: "image/svg+xml",
    sizes: ["any"],
    theme: "light",
  },
  {
    src: dataUri(join(assets, "logo.png"), "image/png"),
    mimeType: "image/png",
    sizes: ["512x512"],
    theme: "dark",
  },
];

mkdirSync(outDir, { recursive: true });

const packEntries = Object.entries(packs)
  .map(([id, raw]) => `  ${asTsString(id)}: ${asTsString(raw)}`)
  .join(",\n");

const iconEntries = icons
  .map(
    (icon) => `  {
    src: ${asTsString(icon.src)},
    mimeType: ${asTsString(icon.mimeType)},
    sizes: ${JSON.stringify(icon.sizes)},
    theme: ${asTsString(icon.theme)},
  }`
  )
  .join(",\n");

const source = `/* AUTO-GENERATED by scripts/embed-content.mjs — do not edit by hand. */
export const EMBEDDED_CONSTITUTION: string = ${asTsString(constitution)};

export const EMBEDDED_PACKS: Record<string, string> = {
${packEntries}
};

export const EMBEDDED_ICONS = [
${iconEntries}
] as const;
`;

writeFileSync(outFile, source);
console.log(
  `Embedded ${packFiles.length} packs + constitution + ${icons.length} icons → src/generated/embedded.ts`
);
